image: docker:20.10.16

services:
  - docker:20.10.16-dind

stages:
  - build
  - deploy

docker-build-staging:
  before_script:
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY_HOST
  stage: build
  only:
    - staging
  script:
    - docker build -t $CI_REGISTRY_HOST/$CI_REGISTRY_USER/$CI_PROJECT_NAME:staging --build-arg ENV_BASE64="${ENV_BASE64_STAGING}" .
    - docker push $CI_REGISTRY_HOST/$CI_REGISTRY_USER/$CI_PROJECT_NAME:staging

deploy-staging:
  stage: deploy
  script:
   - 'curl --location --request POST "${DEPLOY_URL}/api/stacks/dev-${CI_PROJECT_NAME}/redeploy" --header "Authorization: ${DEPLOY_API_TOKEN}"'
  when: manual
  only:
   - staging

docker-build-production:
  before_script:
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY_HOST
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG != "" && $CI_COMMIT_BRANCH == "production"'
  script:
    - docker build -t $CI_REGISTRY_HOST/$CI_REGISTRY_USER/$CI_PROJECT_NAME:$CI_COMMIT_TAG --build-arg ENV_BASE64="${ENV_BASE64_PRODUCTION}" .
    - docker push $CI_REGISTRY_HOST/$CI_REGISTRY_USER/$CI_PROJECT_NAME:$CI_COMMIT_TAG
